class ConstantsTask:
    TASK_ID_MAX_SIZE = 14
    TASK_TITLE_MAX_SIZE = 100
    TASK_DESCRIPTION_MAX_SIZE = 100
    TASK_STATUS_MAX_SIZE = 30
    TASK_STATUS_DEFAULT_VALUE = "OPEN"


class ConstantsTaskStatus:
    TASK_STATUS_ID_MAX_SIZE = 20
    TASK_STATUS_DESCRIPTION_MAX_SIZE = 40


class ConstantsTaskLabel:
    TASK_TAG_ID_MAX_SIZE = 2
    TASK_TAG_DESCRIPTION_MAX_SIZE = 40
