class ConstantsTask:
    TASK_ID_DATE_FORMAT = "%y%m%d"
    TASK_ID_MAX_SIZE = 12
    TASK_TITLE_MAX_SIZE = 100
    TASK_DESCRIPTION_MAX_SIZE = 100
    TASK_STATUS_MAX_SIZE = 30
    TASK_STATUS_DEFAULT_VALUE = "OPEN"
