class ConstantsTask:
    TASK_ID_MAX_SIZE = 10
    TASK_TITTLE_MAX_SIZE = 100
    TASK_DESCRIPTION_MAX_SIZE = 100
    TASK_STATUS_MAX_SIZE = 30
    TASK_STATUS_DEFAULT_VALUE = "0"


class ConstantsTaskStatus:
    TASK_STATUS_ID_MAX_SIZE = 2
    TASK_STATUS_DESCRIPTION_MAX_SIZE = 40


class ConstantsTaskLabel:
    TASK_TAG_ID_MAX_SIZE = 2
    TASK_TAG_DESCRIPTION_MAX_SIZE = 40
