class Constants:
    DEFAULT_ERROR_MESSAGE = "NA"
    DATE_FORMAT = "%Y%m%d"
    TIME_FORMAT = "%H%M%S"
    DATE_TIME_FORMAT = f"{DATE_FORMAT}{TIME_FORMAT}"
    DATE_TIME_FORMAT_MAX_SIZE = 12
    USER_ID_MAX_SIZE = 4
