from enum import Enum


class ErrorKey(str, Enum):
    NOT_IN_ENUM = "NOT_IN_ENUM"
    NOT_UNIQUE_VALUES = "NOT_UNIQUE_VALUES"
    REQUIRED = "REQUIRED"
    INVALID_FORMAT = "INVALID_FORMAT"
    INVALID_VALUE = "INVALID_VALUE"
    MAX_SIZE = "MAX_SIZE"
    CAST_FAIL = "CAST_FAIL"
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    INVALID_JSON_FORMAT = "INVALID_JSON_FORMAT"
    RUNTIME_ERROR = "RUNTIME_ERROR"
    # Repository
    DUPLICATE_KEY = "DUPLICATE_KEY"
    ENTITY_NOT_EXISTS = "ENTITY_NOT_EXISTS"
